Implement Command Stream Loader (CSL) module
codelabs-ch/grub2 pull request #1
Opened 2019-12-06 14:45 UTC by reet-

The Command Stream Loader (CSL) module enables the processing of
TLV-encoded commands. The current protocol version knows the following
commands:

- CMD_CHECK_VERSION
- CMD_META_DATA (ignored)
- CMD_WRITE
- CMD_FILL
- CMD_SET_ENTRY_POINT
- CMD_CHECK_CPUID

The CSL module solves the problem of loading big images on targets with
memory-holes and allows to perform additional (CPUID-based) checks on
the platform. Further protocol iterations will provide commands to check
MSR, control register values and compare arbitrary memory locations.

The existing 'multiboot' module is hacked to only compare the CSL
generated memory image with the one generated via multiboot loader.
This is used to test image equivalence during CI.

2019-12-16 16:36 UTC, Kensan requested changes
Nice, clean implementation, I like it.

Aside from some inline comments a proposed change to the commit message: _The current protocol version ~~knows~~**specifies** the following commands_.

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	if (grub_file_read (file, &vermagic, 8) != 8)
Use `CMD_CHECK_VERSION_DATA_LEN` instead of `8` or alternatively `data_length` if it gets too unwieldy?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +		const grub_uint64_t length)
The dispatched functions use `grub_ssize_t` as data length parameter type. Here length is `grub_uint64_t` which is passed in as data_length argument. This looks OK, as long as [`GRUB_CPU_SIZEOF_VOID_P == 8`](https://github.com/codelabs-ch/grub2/blob/5e5a15872d9e5e7d62a38de426aa35f2b91c2140/include/grub/types.h#L102). Is this always the case?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +				data_length) != data_length)
Since `data_length` includes the address parameter which is consumed by the previous `grub_file_read` call, should the length not be `data_length - 8`?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	grub_memset (get_virtual_current_address (ch), pattern, fill_length);
It seems that [`grub_memset`](https://github.com/codelabs-ch/grub2/blob/5e5a15872d9e5e7d62a38de426aa35f2b91c2140/include/grub/misc.h#L287) uses type `int` for the pattern while here we use `grub_uint64_t`. For patterns that are >32-bit, e.g. `0x0000ffffffffffff`this will probably not produce the expected result.

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +
Drop extra newline.

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	err = grub_relocator_alloc_chunk_addr (relocator, &ch, address, fill_length);
Break line since it is >80 chars.

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +				"%s - unable to read eax / ecx fields",
What's the reason for doing a combined write with shift? Wouldn't it be more straight-forward to read each 32-bit value separately?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	grub_cpuid (leaf, eax, ebx, ecx, edx);
Do we need verify prior to calling this function that CPUID is supported, i.e. using `grub_cpu_is_cpuid_supported()`?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	if (result != value)
Instead of masking each assignment in the switch statement do the masking once here?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +				cmd_names[CMD_CHECK_CPUID], msg, value, result);
Should we increase the size of the message buffer to 65 and explicitly set `msg[64]` to `\0` to ensure the string is null-terminated?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	grub_dprintf ("csl", "Dispatching %s, data length 0x%llx\n", cmd_names[cmd],
The value of `cmd` has not been validated yet so it might be any 16-bit value. It should only be used as index into `cmd_names` after we know it's within the array's bounds. Maybe just print the numeric command value instead?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +static grub_uint64_t entry_point;
Should the variable be prefixed with `grub_csl_`, see [dev guidelines](https://www.gnu.org/software/grub/manual/grub-dev/grub-dev.html#Variables)?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	if (argc == 0)
Should we check for the expected argument count?
  `if (argc != 1)`

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +				"file size not a multiple of 8 bytes");
Should we include the filename in the error message?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +					"unable to read data length");
Should we include the filename in the error message?

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +			return err;
I think we need to close the file before returning the error code.

2019-12-16 16:36 UTC, Kensan commented on grub-core/loader/i386/multiboot_mbi.c
> +		  return 1;
Should we use a GRUB error code constant, e.g. `GRUB_ERR_TEST_FAILURE`?

2019-12-16 16:41 UTC, reet- commented on grub-core/loader/i386/multiboot_mbi.c
> +		  return 1;
No, this is actually **test** error, which has no effect in this case.

2019-12-16 17:42 UTC, reet- commented on grub-core/loader/csl/csl.c
> +	grub_memset (get_virtual_current_address (ch), pattern, fill_length);
Our patterns are mostly `0x0` or `0xffffffffffffffff` and this works as expected. `(int)0xffffffffffffffff` is `-1`, but the binary representation is correct. Nevertheless I see your point.

Should I change it like so:

```C
grub_memset (get_virtual_current_address (ch), pattern & 0xff, fill_length);
```

(The 64-bit patterns are a result of how tau0 represents memory as an array of 64-bit words.)

2019-12-16 18:49 UTC, reet- commented on grub-core/loader/csl/csl.c
> +				data_length) != data_length)
Good catch! This was missing on the generator side, will adjust.

2019-12-16 18:50 UTC, reet- commented on grub-core/loader/csl/csl.c
> +	grub_memset (get_virtual_current_address (ch), pattern, fill_length);
While thinking about this a bit more, I'm going to change the pattern to be 8-bit in the TLV specification (as we have it in the system policy).

2019-12-16 18:54 UTC, reet- commented on grub-core/loader/csl/csl.c
> +				cmd_names[CMD_CHECK_CPUID], msg, value, result);
No, this is enforce by tau0:

```Ada
function To_Msg (Str : String) return Check_Msg_Type
with
   Pre  => Str'Length <= Check_Msg_Type'Last - 1 
              and Str'First + Str'Length < Positive'Last,
   Post => To_Msg'Result (To_Msg'Result'Last) = ASCII.NUL;
```

2019-12-16 19:00 UTC, reet- commented on grub-core/loader/csl/csl.c
> +static grub_uint64_t entry_point;
No, I think the term `global` refers to globally visible variables, not `static`.

2019-12-16 20:55 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +static grub_uint64_t entry_point;
Ok, make sense.

2019-12-16 20:55 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +				cmd_names[CMD_CHECK_CPUID], msg, value, result);
Hm, I am not sure it's a good idea to assume this property here since we are consuming a binary stream of "unknown origin".

2019-12-16 20:55 UTC, Kensan commented on grub-core/loader/i386/multiboot_mbi.c
> +		  return 1;
I don't quite understand, can you elaborate? (The constant [GRUB_ERR_TEST_FAILURE](https://github.com/codelabs-ch/grub2/blob/c7640517a67b860f54a6a8c1ff933a15c136c781/include/grub/err.h#L31) does have the value 1)

2019-12-16 22:04 UTC, reet- commented on grub-core/loader/csl/csl.c
> +				"%s - unable to read eax / ecx fields",
What do you mean by _combined write_?

2019-12-16 22:34 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +				"%s - unable to read eax / ecx fields",
Sorry, that should have said combined read.

2019-12-17 09:43 UTC, reet- commented on grub-core/loader/i386/multiboot_mbi.c
> +		  return 1;
You are right of course. In early testing I used `GRUB_ERR_TEST_FAILURE` until I determined that it did not have the desired effect (which is a boot error). 

But the real problem was that CSL has registered a valid loader already, so the `boot` command was still successful even on `multiboot` failure. To fix that a `grub_loader_unset ()` was required, which is now present.

Long story short, now it is possible to use `GRUB_ERR_TEST_FAILURE`.

2019-12-17 15:10 UTC, Kensan reviewed
Thanks for reworking the patch set so quickly, looks very nice! I've only two questions left.

2019-12-17 15:10 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	content_len = data_length - 8;
Do we need to check of `content_len > GRUB_ULONG_MAX` or is this not possible?

2019-12-17 15:10 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	state.eip = entry_point;
Should we check if `entry_point` was actually set by a `CMD_SET_ENTRY_POINT` command and refuse to boot otherwise?

2019-12-17 15:19 UTC, reet- commented on grub-core/loader/csl/csl.c
> +	content_len = data_length - 8;
`data_length` is [enforced](https://github.com/codelabs-ch/grub2/pull/1/files/e90cf5922a4cd294d7a8b9a66c617168431a3c6d#diff-053edb9d41f9251b82b957ea27dc5a4eR325) to fit into `grub_ssize_t` so `content_len` is `<= GRUB_LONG_MAX - 8` here.

2019-12-17 15:22 UTC, reet- commented on grub-core/loader/csl/csl.c
> +	state.eip = entry_point;
What do you have in mind? An extra boolean or `GRUB_ULONG_MAX` as initial value?

Or we could call `grub_loader_set` in `csl_cmd_set_entry_point`. This leads to a _you must load the kernel first_ when executing the boot command before `csl_cmd_set_entry_point`.

2019-12-17 15:38 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	content_len = data_length - 8;
Great, thanks for the explanation.

2019-12-17 15:40 UTC, Kensan commented on grub-core/loader/csl/csl.c
> +	state.eip = entry_point;
Initializing the `entry_point` and check against this value here with a corresponding error message.

2019-12-17 17:51 UTC, Kensan approved these changes
Looks good to me!

2019-12-17 17:56 UTC, merged