Update CSL to protocol revision 0x8adc5fa2448cb65e
codelabs-ch/grub2 pull request #3
Opened 2020-02-05 17:19 UTC by reet-

- Move to bsbsc directory
- Get rid of `CMD_CHECK_VERSION`
- Get rid of `CMD_META_DATA`
- Skip vendor commands
- Support one-byte `CMD_WRITE`s
- Adjust check string null termination handling

2020-02-06 13:39 UTC, Kensan requested changes
Just some minor comments.

2020-02-06 13:39 UTC, Kensan commented on grub-core/loader/bsbsc/csl.h
> + *  Copyright (C) 2019  codelabs GmbH
2020?

2020-02-06 13:39 UTC, Kensan commented on grub-core/loader/bsbsc/csl.c
> +			/* avoid fseek. otherwise SBS module must implement it. */
Capitalization.

2020-02-06 13:39 UTC, Kensan commented on grub-core/loader/bsbsc/csl.c
> +	if (csl_fs_ops.read (file, &magic, 8) != 8)
Just to double-check: the underlying read implementation already handles the case where the file is less than 8 bytes in size? So magic is always initialized to a sane value even when a read error occurs?

2020-02-07 08:34 UTC, reet- commented on grub-core/loader/bsbsc/csl.c
> +			/* avoid fseek. otherwise SBS module must implement it. */
I use lowercase comments in C, see also line 283.

2020-02-07 08:43 UTC, reet- commented on grub-core/loader/bsbsc/csl.c
> +	if (csl_fs_ops.read (file, &magic, 8) != 8)
When a read error occurs here, an error is returned and processing stops. The `magic` variable is not accessed. The underlying `read` impl. is either `grub_file_read` or the upcoming `sbs_read`, both return < 8 if less bytes are available to read.

2020-02-07 09:29 UTC, Kensan approved these changes
Lgtm

2020-02-07 09:58 UTC, merged